services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://fadikbb2004_db_user:A2B8g7iyeWHMkTOP@cluster0.eaizqsm.mongodb.net/whatsappBot
      - key: true
        value: true
