services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: "node index.js"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: RENDER
        value: true
      - key: MONGO_URI
        sync: false
